### ISSUE TITLE
Does not build against the DigitalPersona One Touch SDK

### ISSUE THREAD

**Issue by mydoghasworms** [tohenk/node-dplib#1]
When trying to install the package, I get the following errors:

```
fatal error C1083: Cannot open include file: 'dpfj.h'
```

(In addition to a whole lot of other messages).

I have Visual Studio 2017 Community Edition installed with MSVC++.

I checked the binding.gyp file, and see that it refers to a different SDK from what I have:

```
"include_dirs": [
	"<!(echo %ProgramFiles%)/DigitalPersona/U.are.U SDK/Include",
```

My SDK is installed at the following location:

C:\Program Files\DigitalPersona\One Touch SDK

This SDK contains the following includes under `C-C++\Include`:

```
dpDefs.h
DPDevClt.h
dpFtrEx.h
dpMatch.h
dpRCodes.h
DpUIApi.h
```

Can you confirm where you got your SDK from and whether it is newer? Can this plugin be made to build against the SDK I have?

**Comment by tohenk** [comment]
You should use Digital Persona U.are.U SDK, not One Touch SDK.

**Comment by mydoghasworms** [comment]
OK, thanks!

**Comment by mydoghasworms** [comment]
@tohenk Would you happen to have a build of your plugin that you could share? You could add it to the files on this repo for download, perhaps?
